### ISSUE TITLE
Preparing/testing for v0.2.0

### ISSUE THREAD

**Issue by shermp** [shermp/NickelDBus#13]
It has been long enough that I feel it's time for a `v0.2.0` release.

If anyone has any concerns about the current state of NDB, speak up now!

If there is anyone who would be willing to test the new functionality re: dialogs, please do.

@clisboa if you want to test with KoboMail, artifacts are available from the *Actions* tab, along with documentation (for the latest run). Any feedback from a potential user would be most appreciated.

**Comment by shermp** [comment]
Thanks for having a test.

If you end up using the new features in KoboMail, you are going to want to do a version test. You can call the `ndbVersion` method for that.

**Comment by clisboa** [comment]
For KoboMail I'm thinking of not having the progress bar.
The use case is to have a few ebooks to download and that's quite fast, the progress bar would just flicker :)
But I'm working on something with rclone (similar to your own but without metadata processing) and for that I think the progress bar is going to be a plus.
I'll look for the ndbVersion and check if it's > 0.2

**Comment by shermp** [comment]
It's finally out! -> https://github.com/shermp/NickelDBus/releases/tag/0.2.0
