### ISSUE TITLE
Compiling with NickelTC docker image

### ISSUE THREAD

**Issue by shavitmichael** [shermp/NickelDBus#7]
I'm not sure how actionable this issue is, but it might at least help others who encounter the same issue.

@pgaskin FYI
The instructions at https://github.com/pgaskin/NickelTC suggest using the following wrapper around docker :

```
#!/bin/bash
exec /usr/bin/docker run --volume="$PWD:$PWD" --user="$(id --user):$(id --group)" --workdir="$PWD" --env=HOME --entrypoint="$(basename "${BASH_SOURCE[0]}")" --rm -it docker.io/geek1011/nickeltc:1 "$@"
```
Calling make cli from the src/cli directory means that only the src/cli is available in the docker image (IIUC), which causes the following error:
> ndb_cli.h:6:36: fatal error: ../interface/ndb_proxy.h: No such file or directory

For now I've worked around this by updating my NickelTC script with this hacky solution:
```
#!/bin/bash
exec /usr/bin/docker run --volume="/home/somebody/Projects/NickelDBus/src:$PWD/.." --user="$(id --user):$(id --group)" --workdir="$PWD" --env=HOME --entrypoint="$(basename "${BASH_SOURCE[0]}")" --rm     -it docker.io/geek1011/nickeltc:1 "$@"
```

P.s: (Big props to y'all on these set of projects by the way :) , this is some really really cool stuff.)

**Comment by shermp** [comment]
Ah, I use NickelTC in a different manner when compiling NDB. I run the build steps inside of the running container interactively, rather than trying to wrap the commands.

Also, `make cli` is meant to be run from the top level directory, and from the top level Makefile FYI.

**Comment by pgaskin** [comment]
I personally tend to run the wrapper from the highest dir, then use the `-C` option to change the directory.

For changing the mounted dir, another option would be to find the top-level git dir with a fallback to then current one.

@shavitmichael, can you open an issue in the NickelTC repo?

> P.s: (Big props to y'all on these set of projects by the way :) , this is some really really cool stuff.)

Nice work with the custom sync stuff too.

**Comment by shavitmichael** [comment]
> I personally tend to run the wrapper from the highest dir, then use the -C option to change the directory.
Aha, yeah that works a lot better, thanks!

**Comment by pgaskin** [comment]
@shermp, can you change the NickelTC image to `ghcr.io/pgaskin/nickeltc:1.0`? I'm planning to remove the one on Docker Hub soon.

**Comment by shermp** [comment]
> @shermp, can you change the NickelTC image to `ghcr.io/pgaskin/nickeltc:1.0`? I'm planning to remove the one on Docker Hub soon.

Done in https://github.com/shermp/NickelDBus/commit/40164cf1654fda381cac573be66d92e86893a13b
